version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: lyvo
      POSTGRES_PASSWORD: lyvo
      POSTGRES_DB: lyvo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lyvo.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
